name: Workflow Staging
on:
  push:
    branches:
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up versioning
        run: echo "Last updated on `date`" > others/version.tex
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: thesis.tex
          latexmk_shell_escape: true
      - name: Move PDF to preview
        run: cp thesis.pdf ./preview
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: pdf-result
          path: thesis.pdf
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./preview
